//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ebis.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbArt : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbArt object using the connection string found in the 'dbArt' section of the application configuration file.
        /// </summary>
        public dbArt() : base("name=dbArt", "dbArt")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbArt object.
        /// </summary>
        public dbArt(string connectionString) : base(connectionString, "dbArt")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbArt object.
        /// </summary>
        public dbArt(EntityConnection connection) : base(connection, "dbArt")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<titul> titul
        {
            get
            {
                if ((_titul == null))
                {
                    _titul = base.CreateObjectSet<titul>("titul");
                }
                return _titul;
            }
        }
        private ObjectSet<titul> _titul;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the titul EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotitul(titul titul)
        {
            base.AddObject("titul", titul);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbArtModel", Name="titul")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class titul : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new titul object.
        /// </summary>
        /// <param name="pk_id">Initial value of the pk_id property.</param>
        /// <param name="titul1">Initial value of the titul1 property.</param>
        /// <param name="autor">Initial value of the autor property.</param>
        /// <param name="poznamka">Initial value of the poznamka property.</param>
        public static titul Createtitul(global::System.Int32 pk_id, global::System.String titul1, global::System.String autor, global::System.String poznamka)
        {
            titul titul = new titul();
            titul.pk_id = pk_id;
            titul.titul1 = titul1;
            titul.autor = autor;
            titul.poznamka = poznamka;
            return titul;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pk_id
        {
            get
            {
                return _pk_id;
            }
            set
            {
                if (_pk_id != value)
                {
                    Onpk_idChanging(value);
                    ReportPropertyChanging("pk_id");
                    _pk_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pk_id");
                    Onpk_idChanged();
                }
            }
        }
        private global::System.Int32 _pk_id;
        partial void Onpk_idChanging(global::System.Int32 value);
        partial void Onpk_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String titul1
        {
            get
            {
                return _titul1;
            }
            set
            {
                Ontitul1Changing(value);
                ReportPropertyChanging("titul1");
                _titul1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("titul1");
                Ontitul1Changed();
            }
        }
        private global::System.String _titul1;
        partial void Ontitul1Changing(global::System.String value);
        partial void Ontitul1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String autor
        {
            get
            {
                return _autor;
            }
            set
            {
                OnautorChanging(value);
                ReportPropertyChanging("autor");
                _autor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("autor");
                OnautorChanged();
            }
        }
        private global::System.String _autor;
        partial void OnautorChanging(global::System.String value);
        partial void OnautorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String poznamka
        {
            get
            {
                return _poznamka;
            }
            set
            {
                OnpoznamkaChanging(value);
                ReportPropertyChanging("poznamka");
                _poznamka = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("poznamka");
                OnpoznamkaChanged();
            }
        }
        private global::System.String _poznamka;
        partial void OnpoznamkaChanging(global::System.String value);
        partial void OnpoznamkaChanged();

        #endregion

    
    }

    #endregion

    
}
