//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("dbArtistModel", "FK_smlouvy_osoby", "osoby", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ebis.Models.osoby), "smlouvy", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ebis.Models.smlouvy), true)]

#endregion

namespace ebis.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbArtist : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbArtist object using the connection string found in the 'dbArtist' section of the application configuration file.
        /// </summary>
        public dbArtist() : base("name=dbArtist", "dbArtist")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbArtist object.
        /// </summary>
        public dbArtist(string connectionString) : base(connectionString, "dbArtist")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbArtist object.
        /// </summary>
        public dbArtist(EntityConnection connection) : base(connection, "dbArtist")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<osoby> osoby
        {
            get
            {
                if ((_osoby == null))
                {
                    _osoby = base.CreateObjectSet<osoby>("osoby");
                }
                return _osoby;
            }
        }
        private ObjectSet<osoby> _osoby;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<osoby_akce> osoby_akce
        {
            get
            {
                if ((_osoby_akce == null))
                {
                    _osoby_akce = base.CreateObjectSet<osoby_akce>("osoby_akce");
                }
                return _osoby_akce;
            }
        }
        private ObjectSet<osoby_akce> _osoby_akce;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<osoby_nastroje> osoby_nastroje
        {
            get
            {
                if ((_osoby_nastroje == null))
                {
                    _osoby_nastroje = base.CreateObjectSet<osoby_nastroje>("osoby_nastroje");
                }
                return _osoby_nastroje;
            }
        }
        private ObjectSet<osoby_nastroje> _osoby_nastroje;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<smlouvy> smlouvy
        {
            get
            {
                if ((_smlouvy == null))
                {
                    _smlouvy = base.CreateObjectSet<smlouvy>("smlouvy");
                }
                return _smlouvy;
            }
        }
        private ObjectSet<smlouvy> _smlouvy;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the osoby EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToosoby(osoby osoby)
        {
            base.AddObject("osoby", osoby);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the osoby_akce EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToosoby_akce(osoby_akce osoby_akce)
        {
            base.AddObject("osoby_akce", osoby_akce);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the osoby_nastroje EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToosoby_nastroje(osoby_nastroje osoby_nastroje)
        {
            base.AddObject("osoby_nastroje", osoby_nastroje);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the smlouvy EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosmlouvy(smlouvy smlouvy)
        {
            base.AddObject("smlouvy", smlouvy);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbArtistModel", Name="osoby")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class osoby : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new osoby object.
        /// </summary>
        /// <param name="pk_id">Initial value of the pk_id property.</param>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="jmeno">Initial value of the jmeno property.</param>
        /// <param name="prijmeni">Initial value of the prijmeni property.</param>
        /// <param name="telefon">Initial value of the telefon property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="mesto">Initial value of the mesto property.</param>
        /// <param name="psc">Initial value of the psc property.</param>
        /// <param name="narodnost">Initial value of the narodnost property.</param>
        /// <param name="cislo_uctu">Initial value of the cislo_uctu property.</param>
        /// <param name="adresa">Initial value of the adresa property.</param>
        /// <param name="datum_narozeni">Initial value of the datum_narozeni property.</param>
        /// <param name="misto_narozeni">Initial value of the misto_narozeni property.</param>
        /// <param name="ic_dic">Initial value of the ic_dic property.</param>
        /// <param name="poznamka">Initial value of the poznamka property.</param>
        public static osoby Createosoby(global::System.Int32 pk_id, global::System.Int32 id, global::System.String jmeno, global::System.String prijmeni, global::System.String telefon, global::System.String email, global::System.String mesto, global::System.String psc, global::System.String narodnost, global::System.String cislo_uctu, global::System.String adresa, global::System.DateTime datum_narozeni, global::System.String misto_narozeni, global::System.Int32 ic_dic, global::System.String poznamka)
        {
            osoby osoby = new osoby();
            osoby.pk_id = pk_id;
            osoby.id = id;
            osoby.jmeno = jmeno;
            osoby.prijmeni = prijmeni;
            osoby.telefon = telefon;
            osoby.email = email;
            osoby.mesto = mesto;
            osoby.psc = psc;
            osoby.narodnost = narodnost;
            osoby.cislo_uctu = cislo_uctu;
            osoby.adresa = adresa;
            osoby.datum_narozeni = datum_narozeni;
            osoby.misto_narozeni = misto_narozeni;
            osoby.ic_dic = ic_dic;
            osoby.poznamka = poznamka;
            return osoby;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pk_id
        {
            get
            {
                return _pk_id;
            }
            set
            {
                if (_pk_id != value)
                {
                    Onpk_idChanging(value);
                    ReportPropertyChanging("pk_id");
                    _pk_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pk_id");
                    Onpk_idChanged();
                }
            }
        }
        private global::System.Int32 _pk_id;
        partial void Onpk_idChanging(global::System.Int32 value);
        partial void Onpk_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String jmeno
        {
            get
            {
                return _jmeno;
            }
            set
            {
                OnjmenoChanging(value);
                ReportPropertyChanging("jmeno");
                _jmeno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("jmeno");
                OnjmenoChanged();
            }
        }
        private global::System.String _jmeno;
        partial void OnjmenoChanging(global::System.String value);
        partial void OnjmenoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String prijmeni
        {
            get
            {
                return _prijmeni;
            }
            set
            {
                OnprijmeniChanging(value);
                ReportPropertyChanging("prijmeni");
                _prijmeni = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("prijmeni");
                OnprijmeniChanged();
            }
        }
        private global::System.String _prijmeni;
        partial void OnprijmeniChanging(global::System.String value);
        partial void OnprijmeniChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String telefon
        {
            get
            {
                return _telefon;
            }
            set
            {
                OntelefonChanging(value);
                ReportPropertyChanging("telefon");
                _telefon = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("telefon");
                OntelefonChanged();
            }
        }
        private global::System.String _telefon;
        partial void OntelefonChanging(global::System.String value);
        partial void OntelefonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mesto
        {
            get
            {
                return _mesto;
            }
            set
            {
                OnmestoChanging(value);
                ReportPropertyChanging("mesto");
                _mesto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mesto");
                OnmestoChanged();
            }
        }
        private global::System.String _mesto;
        partial void OnmestoChanging(global::System.String value);
        partial void OnmestoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String psc
        {
            get
            {
                return _psc;
            }
            set
            {
                OnpscChanging(value);
                ReportPropertyChanging("psc");
                _psc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("psc");
                OnpscChanged();
            }
        }
        private global::System.String _psc;
        partial void OnpscChanging(global::System.String value);
        partial void OnpscChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String narodnost
        {
            get
            {
                return _narodnost;
            }
            set
            {
                OnnarodnostChanging(value);
                ReportPropertyChanging("narodnost");
                _narodnost = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("narodnost");
                OnnarodnostChanged();
            }
        }
        private global::System.String _narodnost;
        partial void OnnarodnostChanging(global::System.String value);
        partial void OnnarodnostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cislo_uctu
        {
            get
            {
                return _cislo_uctu;
            }
            set
            {
                Oncislo_uctuChanging(value);
                ReportPropertyChanging("cislo_uctu");
                _cislo_uctu = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cislo_uctu");
                Oncislo_uctuChanged();
            }
        }
        private global::System.String _cislo_uctu;
        partial void Oncislo_uctuChanging(global::System.String value);
        partial void Oncislo_uctuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String adresa
        {
            get
            {
                return _adresa;
            }
            set
            {
                OnadresaChanging(value);
                ReportPropertyChanging("adresa");
                _adresa = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("adresa");
                OnadresaChanged();
            }
        }
        private global::System.String _adresa;
        partial void OnadresaChanging(global::System.String value);
        partial void OnadresaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime datum_narozeni
        {
            get
            {
                return _datum_narozeni;
            }
            set
            {
                Ondatum_narozeniChanging(value);
                ReportPropertyChanging("datum_narozeni");
                _datum_narozeni = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("datum_narozeni");
                Ondatum_narozeniChanged();
            }
        }
        private global::System.DateTime _datum_narozeni;
        partial void Ondatum_narozeniChanging(global::System.DateTime value);
        partial void Ondatum_narozeniChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String misto_narozeni
        {
            get
            {
                return _misto_narozeni;
            }
            set
            {
                Onmisto_narozeniChanging(value);
                ReportPropertyChanging("misto_narozeni");
                _misto_narozeni = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("misto_narozeni");
                Onmisto_narozeniChanged();
            }
        }
        private global::System.String _misto_narozeni;
        partial void Onmisto_narozeniChanging(global::System.String value);
        partial void Onmisto_narozeniChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ic_dic
        {
            get
            {
                return _ic_dic;
            }
            set
            {
                Onic_dicChanging(value);
                ReportPropertyChanging("ic_dic");
                _ic_dic = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ic_dic");
                Onic_dicChanged();
            }
        }
        private global::System.Int32 _ic_dic;
        partial void Onic_dicChanging(global::System.Int32 value);
        partial void Onic_dicChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String poznamka
        {
            get
            {
                return _poznamka;
            }
            set
            {
                OnpoznamkaChanging(value);
                ReportPropertyChanging("poznamka");
                _poznamka = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("poznamka");
                OnpoznamkaChanged();
            }
        }
        private global::System.String _poznamka;
        partial void OnpoznamkaChanging(global::System.String value);
        partial void OnpoznamkaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbArtistModel", "FK_smlouvy_osoby", "smlouvy")]
        public EntityCollection<smlouvy> smlouvy
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<smlouvy>("dbArtistModel.FK_smlouvy_osoby", "smlouvy");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<smlouvy>("dbArtistModel.FK_smlouvy_osoby", "smlouvy", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbArtistModel", Name="osoby_akce")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class osoby_akce : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new osoby_akce object.
        /// </summary>
        /// <param name="osoby_id">Initial value of the osoby_id property.</param>
        /// <param name="akce_id">Initial value of the akce_id property.</param>
        /// <param name="nastroj_id">Initial value of the nastroj_id property.</param>
        /// <param name="poznamka">Initial value of the poznamka property.</param>
        /// <param name="honorar">Initial value of the honorar property.</param>
        /// <param name="doprava">Initial value of the doprava property.</param>
        /// <param name="srazkova_dan">Initial value of the srazkova_dan property.</param>
        /// <param name="vyplaceno">Initial value of the vyplaceno property.</param>
        public static osoby_akce Createosoby_akce(global::System.Int32 osoby_id, global::System.Int32 akce_id, global::System.Int32 nastroj_id, global::System.String poznamka, global::System.Int32 honorar, global::System.Int32 doprava, global::System.Int32 srazkova_dan, global::System.Int32 vyplaceno)
        {
            osoby_akce osoby_akce = new osoby_akce();
            osoby_akce.osoby_id = osoby_id;
            osoby_akce.akce_id = akce_id;
            osoby_akce.nastroj_id = nastroj_id;
            osoby_akce.poznamka = poznamka;
            osoby_akce.honorar = honorar;
            osoby_akce.doprava = doprava;
            osoby_akce.srazkova_dan = srazkova_dan;
            osoby_akce.vyplaceno = vyplaceno;
            return osoby_akce;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 osoby_id
        {
            get
            {
                return _osoby_id;
            }
            set
            {
                if (_osoby_id != value)
                {
                    Onosoby_idChanging(value);
                    ReportPropertyChanging("osoby_id");
                    _osoby_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("osoby_id");
                    Onosoby_idChanged();
                }
            }
        }
        private global::System.Int32 _osoby_id;
        partial void Onosoby_idChanging(global::System.Int32 value);
        partial void Onosoby_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 akce_id
        {
            get
            {
                return _akce_id;
            }
            set
            {
                if (_akce_id != value)
                {
                    Onakce_idChanging(value);
                    ReportPropertyChanging("akce_id");
                    _akce_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("akce_id");
                    Onakce_idChanged();
                }
            }
        }
        private global::System.Int32 _akce_id;
        partial void Onakce_idChanging(global::System.Int32 value);
        partial void Onakce_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nastroj_id
        {
            get
            {
                return _nastroj_id;
            }
            set
            {
                if (_nastroj_id != value)
                {
                    Onnastroj_idChanging(value);
                    ReportPropertyChanging("nastroj_id");
                    _nastroj_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nastroj_id");
                    Onnastroj_idChanged();
                }
            }
        }
        private global::System.Int32 _nastroj_id;
        partial void Onnastroj_idChanging(global::System.Int32 value);
        partial void Onnastroj_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String poznamka
        {
            get
            {
                return _poznamka;
            }
            set
            {
                OnpoznamkaChanging(value);
                ReportPropertyChanging("poznamka");
                _poznamka = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("poznamka");
                OnpoznamkaChanged();
            }
        }
        private global::System.String _poznamka;
        partial void OnpoznamkaChanging(global::System.String value);
        partial void OnpoznamkaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 honorar
        {
            get
            {
                return _honorar;
            }
            set
            {
                OnhonorarChanging(value);
                ReportPropertyChanging("honorar");
                _honorar = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("honorar");
                OnhonorarChanged();
            }
        }
        private global::System.Int32 _honorar;
        partial void OnhonorarChanging(global::System.Int32 value);
        partial void OnhonorarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 doprava
        {
            get
            {
                return _doprava;
            }
            set
            {
                OndopravaChanging(value);
                ReportPropertyChanging("doprava");
                _doprava = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("doprava");
                OndopravaChanged();
            }
        }
        private global::System.Int32 _doprava;
        partial void OndopravaChanging(global::System.Int32 value);
        partial void OndopravaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 srazkova_dan
        {
            get
            {
                return _srazkova_dan;
            }
            set
            {
                Onsrazkova_danChanging(value);
                ReportPropertyChanging("srazkova_dan");
                _srazkova_dan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("srazkova_dan");
                Onsrazkova_danChanged();
            }
        }
        private global::System.Int32 _srazkova_dan;
        partial void Onsrazkova_danChanging(global::System.Int32 value);
        partial void Onsrazkova_danChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 vyplaceno
        {
            get
            {
                return _vyplaceno;
            }
            set
            {
                OnvyplacenoChanging(value);
                ReportPropertyChanging("vyplaceno");
                _vyplaceno = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vyplaceno");
                OnvyplacenoChanged();
            }
        }
        private global::System.Int32 _vyplaceno;
        partial void OnvyplacenoChanging(global::System.Int32 value);
        partial void OnvyplacenoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbArtistModel", Name="osoby_nastroje")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class osoby_nastroje : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new osoby_nastroje object.
        /// </summary>
        /// <param name="osoby_id">Initial value of the osoby_id property.</param>
        /// <param name="nastroje_id">Initial value of the nastroje_id property.</param>
        public static osoby_nastroje Createosoby_nastroje(global::System.Int32 osoby_id, global::System.Int32 nastroje_id)
        {
            osoby_nastroje osoby_nastroje = new osoby_nastroje();
            osoby_nastroje.osoby_id = osoby_id;
            osoby_nastroje.nastroje_id = nastroje_id;
            return osoby_nastroje;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 osoby_id
        {
            get
            {
                return _osoby_id;
            }
            set
            {
                if (_osoby_id != value)
                {
                    Onosoby_idChanging(value);
                    ReportPropertyChanging("osoby_id");
                    _osoby_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("osoby_id");
                    Onosoby_idChanged();
                }
            }
        }
        private global::System.Int32 _osoby_id;
        partial void Onosoby_idChanging(global::System.Int32 value);
        partial void Onosoby_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nastroje_id
        {
            get
            {
                return _nastroje_id;
            }
            set
            {
                if (_nastroje_id != value)
                {
                    Onnastroje_idChanging(value);
                    ReportPropertyChanging("nastroje_id");
                    _nastroje_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nastroje_id");
                    Onnastroje_idChanged();
                }
            }
        }
        private global::System.Int32 _nastroje_id;
        partial void Onnastroje_idChanging(global::System.Int32 value);
        partial void Onnastroje_idChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbArtistModel", Name="smlouvy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class smlouvy : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new smlouvy object.
        /// </summary>
        /// <param name="pk_id">Initial value of the pk_id property.</param>
        /// <param name="spolecnost">Initial value of the spolecnost property.</param>
        /// <param name="ic">Initial value of the ic property.</param>
        /// <param name="sidlo">Initial value of the sidlo property.</param>
        /// <param name="zastoupeni">Initial value of the zastoupeni property.</param>
        /// <param name="jmeno">Initial value of the jmeno property.</param>
        /// <param name="bytem">Initial value of the bytem property.</param>
        /// <param name="telefon">Initial value of the telefon property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="cislo_uctu">Initial value of the cislo_uctu property.</param>
        /// <param name="datum_narozeni">Initial value of the datum_narozeni property.</param>
        /// <param name="datum_spolecnost">Initial value of the datum_spolecnost property.</param>
        /// <param name="datum_osoba">Initial value of the datum_osoba property.</param>
        /// <param name="osoby_id">Initial value of the osoby_id property.</param>
        /// <param name="text_smlouvy_id">Initial value of the text_smlouvy_id property.</param>
        public static smlouvy Createsmlouvy(global::System.Int32 pk_id, global::System.String spolecnost, global::System.String ic, global::System.String sidlo, global::System.String zastoupeni, global::System.String jmeno, global::System.String bytem, global::System.String telefon, global::System.String email, global::System.String cislo_uctu, global::System.DateTime datum_narozeni, global::System.DateTime datum_spolecnost, global::System.DateTime datum_osoba, global::System.Int32 osoby_id, global::System.Int32 text_smlouvy_id)
        {
            smlouvy smlouvy = new smlouvy();
            smlouvy.pk_id = pk_id;
            smlouvy.spolecnost = spolecnost;
            smlouvy.ic = ic;
            smlouvy.sidlo = sidlo;
            smlouvy.zastoupeni = zastoupeni;
            smlouvy.jmeno = jmeno;
            smlouvy.bytem = bytem;
            smlouvy.telefon = telefon;
            smlouvy.email = email;
            smlouvy.cislo_uctu = cislo_uctu;
            smlouvy.datum_narozeni = datum_narozeni;
            smlouvy.datum_spolecnost = datum_spolecnost;
            smlouvy.datum_osoba = datum_osoba;
            smlouvy.osoby_id = osoby_id;
            smlouvy.text_smlouvy_id = text_smlouvy_id;
            return smlouvy;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pk_id
        {
            get
            {
                return _pk_id;
            }
            set
            {
                if (_pk_id != value)
                {
                    Onpk_idChanging(value);
                    ReportPropertyChanging("pk_id");
                    _pk_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pk_id");
                    Onpk_idChanged();
                }
            }
        }
        private global::System.Int32 _pk_id;
        partial void Onpk_idChanging(global::System.Int32 value);
        partial void Onpk_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String spolecnost
        {
            get
            {
                return _spolecnost;
            }
            set
            {
                OnspolecnostChanging(value);
                ReportPropertyChanging("spolecnost");
                _spolecnost = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("spolecnost");
                OnspolecnostChanged();
            }
        }
        private global::System.String _spolecnost;
        partial void OnspolecnostChanging(global::System.String value);
        partial void OnspolecnostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ic
        {
            get
            {
                return _ic;
            }
            set
            {
                OnicChanging(value);
                ReportPropertyChanging("ic");
                _ic = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ic");
                OnicChanged();
            }
        }
        private global::System.String _ic;
        partial void OnicChanging(global::System.String value);
        partial void OnicChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sidlo
        {
            get
            {
                return _sidlo;
            }
            set
            {
                OnsidloChanging(value);
                ReportPropertyChanging("sidlo");
                _sidlo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sidlo");
                OnsidloChanged();
            }
        }
        private global::System.String _sidlo;
        partial void OnsidloChanging(global::System.String value);
        partial void OnsidloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String zastoupeni
        {
            get
            {
                return _zastoupeni;
            }
            set
            {
                OnzastoupeniChanging(value);
                ReportPropertyChanging("zastoupeni");
                _zastoupeni = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("zastoupeni");
                OnzastoupeniChanged();
            }
        }
        private global::System.String _zastoupeni;
        partial void OnzastoupeniChanging(global::System.String value);
        partial void OnzastoupeniChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String jmeno
        {
            get
            {
                return _jmeno;
            }
            set
            {
                OnjmenoChanging(value);
                ReportPropertyChanging("jmeno");
                _jmeno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("jmeno");
                OnjmenoChanged();
            }
        }
        private global::System.String _jmeno;
        partial void OnjmenoChanging(global::System.String value);
        partial void OnjmenoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String bytem
        {
            get
            {
                return _bytem;
            }
            set
            {
                OnbytemChanging(value);
                ReportPropertyChanging("bytem");
                _bytem = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("bytem");
                OnbytemChanged();
            }
        }
        private global::System.String _bytem;
        partial void OnbytemChanging(global::System.String value);
        partial void OnbytemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String telefon
        {
            get
            {
                return _telefon;
            }
            set
            {
                OntelefonChanging(value);
                ReportPropertyChanging("telefon");
                _telefon = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("telefon");
                OntelefonChanged();
            }
        }
        private global::System.String _telefon;
        partial void OntelefonChanging(global::System.String value);
        partial void OntelefonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cislo_uctu
        {
            get
            {
                return _cislo_uctu;
            }
            set
            {
                Oncislo_uctuChanging(value);
                ReportPropertyChanging("cislo_uctu");
                _cislo_uctu = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cislo_uctu");
                Oncislo_uctuChanged();
            }
        }
        private global::System.String _cislo_uctu;
        partial void Oncislo_uctuChanging(global::System.String value);
        partial void Oncislo_uctuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime datum_narozeni
        {
            get
            {
                return _datum_narozeni;
            }
            set
            {
                Ondatum_narozeniChanging(value);
                ReportPropertyChanging("datum_narozeni");
                _datum_narozeni = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("datum_narozeni");
                Ondatum_narozeniChanged();
            }
        }
        private global::System.DateTime _datum_narozeni;
        partial void Ondatum_narozeniChanging(global::System.DateTime value);
        partial void Ondatum_narozeniChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime datum_spolecnost
        {
            get
            {
                return _datum_spolecnost;
            }
            set
            {
                Ondatum_spolecnostChanging(value);
                ReportPropertyChanging("datum_spolecnost");
                _datum_spolecnost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("datum_spolecnost");
                Ondatum_spolecnostChanged();
            }
        }
        private global::System.DateTime _datum_spolecnost;
        partial void Ondatum_spolecnostChanging(global::System.DateTime value);
        partial void Ondatum_spolecnostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime datum_osoba
        {
            get
            {
                return _datum_osoba;
            }
            set
            {
                Ondatum_osobaChanging(value);
                ReportPropertyChanging("datum_osoba");
                _datum_osoba = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("datum_osoba");
                Ondatum_osobaChanged();
            }
        }
        private global::System.DateTime _datum_osoba;
        partial void Ondatum_osobaChanging(global::System.DateTime value);
        partial void Ondatum_osobaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 osoby_id
        {
            get
            {
                return _osoby_id;
            }
            set
            {
                Onosoby_idChanging(value);
                ReportPropertyChanging("osoby_id");
                _osoby_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("osoby_id");
                Onosoby_idChanged();
            }
        }
        private global::System.Int32 _osoby_id;
        partial void Onosoby_idChanging(global::System.Int32 value);
        partial void Onosoby_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 text_smlouvy_id
        {
            get
            {
                return _text_smlouvy_id;
            }
            set
            {
                Ontext_smlouvy_idChanging(value);
                ReportPropertyChanging("text_smlouvy_id");
                _text_smlouvy_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("text_smlouvy_id");
                Ontext_smlouvy_idChanged();
            }
        }
        private global::System.Int32 _text_smlouvy_id;
        partial void Ontext_smlouvy_idChanging(global::System.Int32 value);
        partial void Ontext_smlouvy_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbArtistModel", "FK_smlouvy_osoby", "osoby")]
        public osoby osoby
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<osoby>("dbArtistModel.FK_smlouvy_osoby", "osoby").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<osoby>("dbArtistModel.FK_smlouvy_osoby", "osoby").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<osoby> osobyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<osoby>("dbArtistModel.FK_smlouvy_osoby", "osoby");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<osoby>("dbArtistModel.FK_smlouvy_osoby", "osoby", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
