//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("dbEventModel", "FK_akce_naklady_akce", "akce", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ebis.Models.akce), "akce_naklady", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ebis.Models.akce_naklady), true)]
[assembly: EdmRelationshipAttribute("dbEventModel", "FK_akce_produkcni_listy_akce", "akce", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ebis.Models.akce), "akce_produkcni_listy", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ebis.Models.akce_produkcni_listy), true)]
[assembly: EdmRelationshipAttribute("dbEventModel", "FK_fermany_akce", "akce", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ebis.Models.akce), "fermany", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ebis.Models.fermany), true)]
[assembly: EdmRelationshipAttribute("dbEventModel", "FK_osoby_akce_akce", "akce", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ebis.Models.akce), "osoby_akce", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ebis.Models.osoby_akce), true)]
[assembly: EdmRelationshipAttribute("dbEventModel", "FK_ubytovani_akce", "akce", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ebis.Models.akce), "ubytovani", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ebis.Models.ubytovani), true)]

#endregion

namespace ebis.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbEvent : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbEvent object using the connection string found in the 'dbEvent' section of the application configuration file.
        /// </summary>
        public dbEvent() : base("name=dbEvent", "dbEvent")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbEvent object.
        /// </summary>
        public dbEvent(string connectionString) : base(connectionString, "dbEvent")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbEvent object.
        /// </summary>
        public dbEvent(EntityConnection connection) : base(connection, "dbEvent")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<akce> akce
        {
            get
            {
                if ((_akce == null))
                {
                    _akce = base.CreateObjectSet<akce>("akce");
                }
                return _akce;
            }
        }
        private ObjectSet<akce> _akce;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<akce_naklady> akce_naklady
        {
            get
            {
                if ((_akce_naklady == null))
                {
                    _akce_naklady = base.CreateObjectSet<akce_naklady>("akce_naklady");
                }
                return _akce_naklady;
            }
        }
        private ObjectSet<akce_naklady> _akce_naklady;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<akce_produkcni_listy> akce_produkcni_listy
        {
            get
            {
                if ((_akce_produkcni_listy == null))
                {
                    _akce_produkcni_listy = base.CreateObjectSet<akce_produkcni_listy>("akce_produkcni_listy");
                }
                return _akce_produkcni_listy;
            }
        }
        private ObjectSet<akce_produkcni_listy> _akce_produkcni_listy;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<fermany> fermany
        {
            get
            {
                if ((_fermany == null))
                {
                    _fermany = base.CreateObjectSet<fermany>("fermany");
                }
                return _fermany;
            }
        }
        private ObjectSet<fermany> _fermany;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<osoby_akce> osoby_akce
        {
            get
            {
                if ((_osoby_akce == null))
                {
                    _osoby_akce = base.CreateObjectSet<osoby_akce>("osoby_akce");
                }
                return _osoby_akce;
            }
        }
        private ObjectSet<osoby_akce> _osoby_akce;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ubytovani> ubytovani
        {
            get
            {
                if ((_ubytovani == null))
                {
                    _ubytovani = base.CreateObjectSet<ubytovani>("ubytovani");
                }
                return _ubytovani;
            }
        }
        private ObjectSet<ubytovani> _ubytovani;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the akce EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToakce(akce akce)
        {
            base.AddObject("akce", akce);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the akce_naklady EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToakce_naklady(akce_naklady akce_naklady)
        {
            base.AddObject("akce_naklady", akce_naklady);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the akce_produkcni_listy EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToakce_produkcni_listy(akce_produkcni_listy akce_produkcni_listy)
        {
            base.AddObject("akce_produkcni_listy", akce_produkcni_listy);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the fermany EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTofermany(fermany fermany)
        {
            base.AddObject("fermany", fermany);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the osoby_akce EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToosoby_akce(osoby_akce osoby_akce)
        {
            base.AddObject("osoby_akce", osoby_akce);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ubytovani EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToubytovani(ubytovani ubytovani)
        {
            base.AddObject("ubytovani", ubytovani);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbEventModel", Name="akce")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class akce : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new akce object.
        /// </summary>
        /// <param name="pk_id">Initial value of the pk_id property.</param>
        /// <param name="jmeno">Initial value of the jmeno property.</param>
        /// <param name="popis">Initial value of the popis property.</param>
        /// <param name="titul_id">Initial value of the titul_id property.</param>
        /// <param name="datum">Initial value of the datum property.</param>
        /// <param name="cas">Initial value of the cas property.</param>
        public static akce Createakce(global::System.Int32 pk_id, global::System.String jmeno, global::System.String popis, global::System.Int32 titul_id, global::System.DateTime datum, global::System.String cas)
        {
            akce akce = new akce();
            akce.pk_id = pk_id;
            akce.jmeno = jmeno;
            akce.popis = popis;
            akce.titul_id = titul_id;
            akce.datum = datum;
            akce.cas = cas;
            return akce;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pk_id
        {
            get
            {
                return _pk_id;
            }
            set
            {
                if (_pk_id != value)
                {
                    Onpk_idChanging(value);
                    ReportPropertyChanging("pk_id");
                    _pk_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pk_id");
                    Onpk_idChanged();
                }
            }
        }
        private global::System.Int32 _pk_id;
        partial void Onpk_idChanging(global::System.Int32 value);
        partial void Onpk_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String jmeno
        {
            get
            {
                return _jmeno;
            }
            set
            {
                OnjmenoChanging(value);
                ReportPropertyChanging("jmeno");
                _jmeno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("jmeno");
                OnjmenoChanged();
            }
        }
        private global::System.String _jmeno;
        partial void OnjmenoChanging(global::System.String value);
        partial void OnjmenoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String popis
        {
            get
            {
                return _popis;
            }
            set
            {
                OnpopisChanging(value);
                ReportPropertyChanging("popis");
                _popis = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("popis");
                OnpopisChanged();
            }
        }
        private global::System.String _popis;
        partial void OnpopisChanging(global::System.String value);
        partial void OnpopisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 titul_id
        {
            get
            {
                return _titul_id;
            }
            set
            {
                Ontitul_idChanging(value);
                ReportPropertyChanging("titul_id");
                _titul_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("titul_id");
                Ontitul_idChanged();
            }
        }
        private global::System.Int32 _titul_id;
        partial void Ontitul_idChanging(global::System.Int32 value);
        partial void Ontitul_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime datum
        {
            get
            {
                return _datum;
            }
            set
            {
                OndatumChanging(value);
                ReportPropertyChanging("datum");
                _datum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("datum");
                OndatumChanged();
            }
        }
        private global::System.DateTime _datum;
        partial void OndatumChanging(global::System.DateTime value);
        partial void OndatumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cas
        {
            get
            {
                return _cas;
            }
            set
            {
                OncasChanging(value);
                ReportPropertyChanging("cas");
                _cas = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cas");
                OncasChanged();
            }
        }
        private global::System.String _cas;
        partial void OncasChanging(global::System.String value);
        partial void OncasChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbEventModel", "FK_akce_naklady_akce", "akce_naklady")]
        public EntityCollection<akce_naklady> akce_naklady
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<akce_naklady>("dbEventModel.FK_akce_naklady_akce", "akce_naklady");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<akce_naklady>("dbEventModel.FK_akce_naklady_akce", "akce_naklady", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbEventModel", "FK_akce_produkcni_listy_akce", "akce_produkcni_listy")]
        public EntityCollection<akce_produkcni_listy> akce_produkcni_listy
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<akce_produkcni_listy>("dbEventModel.FK_akce_produkcni_listy_akce", "akce_produkcni_listy");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<akce_produkcni_listy>("dbEventModel.FK_akce_produkcni_listy_akce", "akce_produkcni_listy", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbEventModel", "FK_fermany_akce", "fermany")]
        public EntityCollection<fermany> fermany
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<fermany>("dbEventModel.FK_fermany_akce", "fermany");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<fermany>("dbEventModel.FK_fermany_akce", "fermany", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbEventModel", "FK_osoby_akce_akce", "osoby_akce")]
        public EntityCollection<osoby_akce> osoby_akce
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<osoby_akce>("dbEventModel.FK_osoby_akce_akce", "osoby_akce");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<osoby_akce>("dbEventModel.FK_osoby_akce_akce", "osoby_akce", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbEventModel", "FK_ubytovani_akce", "ubytovani")]
        public EntityCollection<ubytovani> ubytovani
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ubytovani>("dbEventModel.FK_ubytovani_akce", "ubytovani");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ubytovani>("dbEventModel.FK_ubytovani_akce", "ubytovani", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbEventModel", Name="akce_naklady")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class akce_naklady : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new akce_naklady object.
        /// </summary>
        /// <param name="akce_id">Initial value of the akce_id property.</param>
        /// <param name="naklady_id">Initial value of the naklady_id property.</param>
        /// <param name="cena">Initial value of the cena property.</param>
        public static akce_naklady Createakce_naklady(global::System.Int32 akce_id, global::System.Int32 naklady_id, global::System.Int32 cena)
        {
            akce_naklady akce_naklady = new akce_naklady();
            akce_naklady.akce_id = akce_id;
            akce_naklady.naklady_id = naklady_id;
            akce_naklady.cena = cena;
            return akce_naklady;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 akce_id
        {
            get
            {
                return _akce_id;
            }
            set
            {
                if (_akce_id != value)
                {
                    Onakce_idChanging(value);
                    ReportPropertyChanging("akce_id");
                    _akce_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("akce_id");
                    Onakce_idChanged();
                }
            }
        }
        private global::System.Int32 _akce_id;
        partial void Onakce_idChanging(global::System.Int32 value);
        partial void Onakce_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 naklady_id
        {
            get
            {
                return _naklady_id;
            }
            set
            {
                if (_naklady_id != value)
                {
                    Onnaklady_idChanging(value);
                    ReportPropertyChanging("naklady_id");
                    _naklady_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("naklady_id");
                    Onnaklady_idChanged();
                }
            }
        }
        private global::System.Int32 _naklady_id;
        partial void Onnaklady_idChanging(global::System.Int32 value);
        partial void Onnaklady_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cena
        {
            get
            {
                return _cena;
            }
            set
            {
                OncenaChanging(value);
                ReportPropertyChanging("cena");
                _cena = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cena");
                OncenaChanged();
            }
        }
        private global::System.Int32 _cena;
        partial void OncenaChanging(global::System.Int32 value);
        partial void OncenaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbEventModel", "FK_akce_naklady_akce", "akce")]
        public akce akce
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akce>("dbEventModel.FK_akce_naklady_akce", "akce").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akce>("dbEventModel.FK_akce_naklady_akce", "akce").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<akce> akceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akce>("dbEventModel.FK_akce_naklady_akce", "akce");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<akce>("dbEventModel.FK_akce_naklady_akce", "akce", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbEventModel", Name="akce_produkcni_listy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class akce_produkcni_listy : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new akce_produkcni_listy object.
        /// </summary>
        /// <param name="akce_id">Initial value of the akce_id property.</param>
        /// <param name="produkcni_listy_id">Initial value of the produkcni_listy_id property.</param>
        /// <param name="poznamka">Initial value of the poznamka property.</param>
        /// <param name="termin">Initial value of the termin property.</param>
        /// <param name="status">Initial value of the status property.</param>
        /// <param name="zodpovedna_osoba">Initial value of the zodpovedna_osoba property.</param>
        public static akce_produkcni_listy Createakce_produkcni_listy(global::System.Int32 akce_id, global::System.Int32 produkcni_listy_id, global::System.String poznamka, global::System.String termin, global::System.Int32 status, global::System.String zodpovedna_osoba)
        {
            akce_produkcni_listy akce_produkcni_listy = new akce_produkcni_listy();
            akce_produkcni_listy.akce_id = akce_id;
            akce_produkcni_listy.produkcni_listy_id = produkcni_listy_id;
            akce_produkcni_listy.poznamka = poznamka;
            akce_produkcni_listy.termin = termin;
            akce_produkcni_listy.status = status;
            akce_produkcni_listy.zodpovedna_osoba = zodpovedna_osoba;
            return akce_produkcni_listy;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 akce_id
        {
            get
            {
                return _akce_id;
            }
            set
            {
                if (_akce_id != value)
                {
                    Onakce_idChanging(value);
                    ReportPropertyChanging("akce_id");
                    _akce_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("akce_id");
                    Onakce_idChanged();
                }
            }
        }
        private global::System.Int32 _akce_id;
        partial void Onakce_idChanging(global::System.Int32 value);
        partial void Onakce_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 produkcni_listy_id
        {
            get
            {
                return _produkcni_listy_id;
            }
            set
            {
                if (_produkcni_listy_id != value)
                {
                    Onprodukcni_listy_idChanging(value);
                    ReportPropertyChanging("produkcni_listy_id");
                    _produkcni_listy_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("produkcni_listy_id");
                    Onprodukcni_listy_idChanged();
                }
            }
        }
        private global::System.Int32 _produkcni_listy_id;
        partial void Onprodukcni_listy_idChanging(global::System.Int32 value);
        partial void Onprodukcni_listy_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String poznamka
        {
            get
            {
                return _poznamka;
            }
            set
            {
                OnpoznamkaChanging(value);
                ReportPropertyChanging("poznamka");
                _poznamka = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("poznamka");
                OnpoznamkaChanged();
            }
        }
        private global::System.String _poznamka;
        partial void OnpoznamkaChanging(global::System.String value);
        partial void OnpoznamkaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String termin
        {
            get
            {
                return _termin;
            }
            set
            {
                OnterminChanging(value);
                ReportPropertyChanging("termin");
                _termin = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("termin");
                OnterminChanged();
            }
        }
        private global::System.String _termin;
        partial void OnterminChanging(global::System.String value);
        partial void OnterminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.Int32 _status;
        partial void OnstatusChanging(global::System.Int32 value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String zodpovedna_osoba
        {
            get
            {
                return _zodpovedna_osoba;
            }
            set
            {
                Onzodpovedna_osobaChanging(value);
                ReportPropertyChanging("zodpovedna_osoba");
                _zodpovedna_osoba = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("zodpovedna_osoba");
                Onzodpovedna_osobaChanged();
            }
        }
        private global::System.String _zodpovedna_osoba;
        partial void Onzodpovedna_osobaChanging(global::System.String value);
        partial void Onzodpovedna_osobaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbEventModel", "FK_akce_produkcni_listy_akce", "akce")]
        public akce akce
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akce>("dbEventModel.FK_akce_produkcni_listy_akce", "akce").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akce>("dbEventModel.FK_akce_produkcni_listy_akce", "akce").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<akce> akceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akce>("dbEventModel.FK_akce_produkcni_listy_akce", "akce");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<akce>("dbEventModel.FK_akce_produkcni_listy_akce", "akce", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbEventModel", Name="fermany")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class fermany : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new fermany object.
        /// </summary>
        /// <param name="pk_id">Initial value of the pk_id property.</param>
        /// <param name="akce_id">Initial value of the akce_id property.</param>
        /// <param name="lokace_id">Initial value of the lokace_id property.</param>
        /// <param name="datum">Initial value of the datum property.</param>
        /// <param name="cas">Initial value of the cas property.</param>
        /// <param name="orchestr">Initial value of the orchestr property.</param>
        /// <param name="sbor">Initial value of the sbor property.</param>
        /// <param name="solisti">Initial value of the solisti property.</param>
        public static fermany Createfermany(global::System.Int32 pk_id, global::System.Int32 akce_id, global::System.Int32 lokace_id, global::System.DateTime datum, global::System.String cas, global::System.String orchestr, global::System.String sbor, global::System.String solisti)
        {
            fermany fermany = new fermany();
            fermany.pk_id = pk_id;
            fermany.akce_id = akce_id;
            fermany.lokace_id = lokace_id;
            fermany.datum = datum;
            fermany.cas = cas;
            fermany.orchestr = orchestr;
            fermany.sbor = sbor;
            fermany.solisti = solisti;
            return fermany;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pk_id
        {
            get
            {
                return _pk_id;
            }
            set
            {
                if (_pk_id != value)
                {
                    Onpk_idChanging(value);
                    ReportPropertyChanging("pk_id");
                    _pk_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pk_id");
                    Onpk_idChanged();
                }
            }
        }
        private global::System.Int32 _pk_id;
        partial void Onpk_idChanging(global::System.Int32 value);
        partial void Onpk_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 akce_id
        {
            get
            {
                return _akce_id;
            }
            set
            {
                Onakce_idChanging(value);
                ReportPropertyChanging("akce_id");
                _akce_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("akce_id");
                Onakce_idChanged();
            }
        }
        private global::System.Int32 _akce_id;
        partial void Onakce_idChanging(global::System.Int32 value);
        partial void Onakce_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 lokace_id
        {
            get
            {
                return _lokace_id;
            }
            set
            {
                Onlokace_idChanging(value);
                ReportPropertyChanging("lokace_id");
                _lokace_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lokace_id");
                Onlokace_idChanged();
            }
        }
        private global::System.Int32 _lokace_id;
        partial void Onlokace_idChanging(global::System.Int32 value);
        partial void Onlokace_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime datum
        {
            get
            {
                return _datum;
            }
            set
            {
                OndatumChanging(value);
                ReportPropertyChanging("datum");
                _datum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("datum");
                OndatumChanged();
            }
        }
        private global::System.DateTime _datum;
        partial void OndatumChanging(global::System.DateTime value);
        partial void OndatumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cas
        {
            get
            {
                return _cas;
            }
            set
            {
                OncasChanging(value);
                ReportPropertyChanging("cas");
                _cas = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cas");
                OncasChanged();
            }
        }
        private global::System.String _cas;
        partial void OncasChanging(global::System.String value);
        partial void OncasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String orchestr
        {
            get
            {
                return _orchestr;
            }
            set
            {
                OnorchestrChanging(value);
                ReportPropertyChanging("orchestr");
                _orchestr = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("orchestr");
                OnorchestrChanged();
            }
        }
        private global::System.String _orchestr;
        partial void OnorchestrChanging(global::System.String value);
        partial void OnorchestrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sbor
        {
            get
            {
                return _sbor;
            }
            set
            {
                OnsborChanging(value);
                ReportPropertyChanging("sbor");
                _sbor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sbor");
                OnsborChanged();
            }
        }
        private global::System.String _sbor;
        partial void OnsborChanging(global::System.String value);
        partial void OnsborChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String solisti
        {
            get
            {
                return _solisti;
            }
            set
            {
                OnsolistiChanging(value);
                ReportPropertyChanging("solisti");
                _solisti = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("solisti");
                OnsolistiChanged();
            }
        }
        private global::System.String _solisti;
        partial void OnsolistiChanging(global::System.String value);
        partial void OnsolistiChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbEventModel", "FK_fermany_akce", "akce")]
        public akce akce
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akce>("dbEventModel.FK_fermany_akce", "akce").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akce>("dbEventModel.FK_fermany_akce", "akce").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<akce> akceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akce>("dbEventModel.FK_fermany_akce", "akce");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<akce>("dbEventModel.FK_fermany_akce", "akce", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbEventModel", Name="osoby_akce")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class osoby_akce : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new osoby_akce object.
        /// </summary>
        /// <param name="osoby_id">Initial value of the osoby_id property.</param>
        /// <param name="akce_id">Initial value of the akce_id property.</param>
        /// <param name="nastroje_id">Initial value of the nastroje_id property.</param>
        /// <param name="poznamka">Initial value of the poznamka property.</param>
        /// <param name="honorar">Initial value of the honorar property.</param>
        /// <param name="doprava">Initial value of the doprava property.</param>
        /// <param name="srazkova_dan">Initial value of the srazkova_dan property.</param>
        /// <param name="vyplaceno">Initial value of the vyplaceno property.</param>
        public static osoby_akce Createosoby_akce(global::System.Int32 osoby_id, global::System.Int32 akce_id, global::System.Int32 nastroje_id, global::System.String poznamka, global::System.Int32 honorar, global::System.Int32 doprava, global::System.Int32 srazkova_dan, global::System.Int32 vyplaceno)
        {
            osoby_akce osoby_akce = new osoby_akce();
            osoby_akce.osoby_id = osoby_id;
            osoby_akce.akce_id = akce_id;
            osoby_akce.nastroje_id = nastroje_id;
            osoby_akce.poznamka = poznamka;
            osoby_akce.honorar = honorar;
            osoby_akce.doprava = doprava;
            osoby_akce.srazkova_dan = srazkova_dan;
            osoby_akce.vyplaceno = vyplaceno;
            return osoby_akce;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 osoby_id
        {
            get
            {
                return _osoby_id;
            }
            set
            {
                if (_osoby_id != value)
                {
                    Onosoby_idChanging(value);
                    ReportPropertyChanging("osoby_id");
                    _osoby_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("osoby_id");
                    Onosoby_idChanged();
                }
            }
        }
        private global::System.Int32 _osoby_id;
        partial void Onosoby_idChanging(global::System.Int32 value);
        partial void Onosoby_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 akce_id
        {
            get
            {
                return _akce_id;
            }
            set
            {
                if (_akce_id != value)
                {
                    Onakce_idChanging(value);
                    ReportPropertyChanging("akce_id");
                    _akce_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("akce_id");
                    Onakce_idChanged();
                }
            }
        }
        private global::System.Int32 _akce_id;
        partial void Onakce_idChanging(global::System.Int32 value);
        partial void Onakce_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nastroje_id
        {
            get
            {
                return _nastroje_id;
            }
            set
            {
                if (_nastroje_id != value)
                {
                    Onnastroje_idChanging(value);
                    ReportPropertyChanging("nastroje_id");
                    _nastroje_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nastroje_id");
                    Onnastroje_idChanged();
                }
            }
        }
        private global::System.Int32 _nastroje_id;
        partial void Onnastroje_idChanging(global::System.Int32 value);
        partial void Onnastroje_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String poznamka
        {
            get
            {
                return _poznamka;
            }
            set
            {
                OnpoznamkaChanging(value);
                ReportPropertyChanging("poznamka");
                _poznamka = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("poznamka");
                OnpoznamkaChanged();
            }
        }
        private global::System.String _poznamka;
        partial void OnpoznamkaChanging(global::System.String value);
        partial void OnpoznamkaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 honorar
        {
            get
            {
                return _honorar;
            }
            set
            {
                OnhonorarChanging(value);
                ReportPropertyChanging("honorar");
                _honorar = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("honorar");
                OnhonorarChanged();
            }
        }
        private global::System.Int32 _honorar;
        partial void OnhonorarChanging(global::System.Int32 value);
        partial void OnhonorarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 doprava
        {
            get
            {
                return _doprava;
            }
            set
            {
                OndopravaChanging(value);
                ReportPropertyChanging("doprava");
                _doprava = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("doprava");
                OndopravaChanged();
            }
        }
        private global::System.Int32 _doprava;
        partial void OndopravaChanging(global::System.Int32 value);
        partial void OndopravaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 srazkova_dan
        {
            get
            {
                return _srazkova_dan;
            }
            set
            {
                Onsrazkova_danChanging(value);
                ReportPropertyChanging("srazkova_dan");
                _srazkova_dan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("srazkova_dan");
                Onsrazkova_danChanged();
            }
        }
        private global::System.Int32 _srazkova_dan;
        partial void Onsrazkova_danChanging(global::System.Int32 value);
        partial void Onsrazkova_danChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 vyplaceno
        {
            get
            {
                return _vyplaceno;
            }
            set
            {
                OnvyplacenoChanging(value);
                ReportPropertyChanging("vyplaceno");
                _vyplaceno = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vyplaceno");
                OnvyplacenoChanged();
            }
        }
        private global::System.Int32 _vyplaceno;
        partial void OnvyplacenoChanging(global::System.Int32 value);
        partial void OnvyplacenoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbEventModel", "FK_osoby_akce_akce", "akce")]
        public akce akce
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akce>("dbEventModel.FK_osoby_akce_akce", "akce").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akce>("dbEventModel.FK_osoby_akce_akce", "akce").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<akce> akceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akce>("dbEventModel.FK_osoby_akce_akce", "akce");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<akce>("dbEventModel.FK_osoby_akce_akce", "akce", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbEventModel", Name="ubytovani")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ubytovani : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ubytovani object.
        /// </summary>
        /// <param name="pk_id">Initial value of the pk_id property.</param>
        /// <param name="osoby_id">Initial value of the osoby_id property.</param>
        /// <param name="lokace_id">Initial value of the lokace_id property.</param>
        /// <param name="akce_id">Initial value of the akce_id property.</param>
        /// <param name="pokoj">Initial value of the pokoj property.</param>
        /// <param name="cena1">Initial value of the cena1 property.</param>
        /// <param name="cena2">Initial value of the cena2 property.</param>
        /// <param name="cena3">Initial value of the cena3 property.</param>
        public static ubytovani Createubytovani(global::System.Int32 pk_id, global::System.Int32 osoby_id, global::System.Int32 lokace_id, global::System.Int32 akce_id, global::System.Int32 pokoj, global::System.Int32 cena1, global::System.Int32 cena2, global::System.Int32 cena3)
        {
            ubytovani ubytovani = new ubytovani();
            ubytovani.pk_id = pk_id;
            ubytovani.osoby_id = osoby_id;
            ubytovani.lokace_id = lokace_id;
            ubytovani.akce_id = akce_id;
            ubytovani.pokoj = pokoj;
            ubytovani.cena1 = cena1;
            ubytovani.cena2 = cena2;
            ubytovani.cena3 = cena3;
            return ubytovani;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pk_id
        {
            get
            {
                return _pk_id;
            }
            set
            {
                if (_pk_id != value)
                {
                    Onpk_idChanging(value);
                    ReportPropertyChanging("pk_id");
                    _pk_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pk_id");
                    Onpk_idChanged();
                }
            }
        }
        private global::System.Int32 _pk_id;
        partial void Onpk_idChanging(global::System.Int32 value);
        partial void Onpk_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 osoby_id
        {
            get
            {
                return _osoby_id;
            }
            set
            {
                Onosoby_idChanging(value);
                ReportPropertyChanging("osoby_id");
                _osoby_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("osoby_id");
                Onosoby_idChanged();
            }
        }
        private global::System.Int32 _osoby_id;
        partial void Onosoby_idChanging(global::System.Int32 value);
        partial void Onosoby_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 lokace_id
        {
            get
            {
                return _lokace_id;
            }
            set
            {
                Onlokace_idChanging(value);
                ReportPropertyChanging("lokace_id");
                _lokace_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lokace_id");
                Onlokace_idChanged();
            }
        }
        private global::System.Int32 _lokace_id;
        partial void Onlokace_idChanging(global::System.Int32 value);
        partial void Onlokace_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 akce_id
        {
            get
            {
                return _akce_id;
            }
            set
            {
                Onakce_idChanging(value);
                ReportPropertyChanging("akce_id");
                _akce_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("akce_id");
                Onakce_idChanged();
            }
        }
        private global::System.Int32 _akce_id;
        partial void Onakce_idChanging(global::System.Int32 value);
        partial void Onakce_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pokoj
        {
            get
            {
                return _pokoj;
            }
            set
            {
                OnpokojChanging(value);
                ReportPropertyChanging("pokoj");
                _pokoj = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pokoj");
                OnpokojChanged();
            }
        }
        private global::System.Int32 _pokoj;
        partial void OnpokojChanging(global::System.Int32 value);
        partial void OnpokojChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cena1
        {
            get
            {
                return _cena1;
            }
            set
            {
                Oncena1Changing(value);
                ReportPropertyChanging("cena1");
                _cena1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cena1");
                Oncena1Changed();
            }
        }
        private global::System.Int32 _cena1;
        partial void Oncena1Changing(global::System.Int32 value);
        partial void Oncena1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cena2
        {
            get
            {
                return _cena2;
            }
            set
            {
                Oncena2Changing(value);
                ReportPropertyChanging("cena2");
                _cena2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cena2");
                Oncena2Changed();
            }
        }
        private global::System.Int32 _cena2;
        partial void Oncena2Changing(global::System.Int32 value);
        partial void Oncena2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cena3
        {
            get
            {
                return _cena3;
            }
            set
            {
                Oncena3Changing(value);
                ReportPropertyChanging("cena3");
                _cena3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cena3");
                Oncena3Changed();
            }
        }
        private global::System.Int32 _cena3;
        partial void Oncena3Changing(global::System.Int32 value);
        partial void Oncena3Changed();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbEventModel", "FK_ubytovani_akce", "akce")]
        public akce akce
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akce>("dbEventModel.FK_ubytovani_akce", "akce").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akce>("dbEventModel.FK_ubytovani_akce", "akce").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<akce> akceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<akce>("dbEventModel.FK_ubytovani_akce", "akce");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<akce>("dbEventModel.FK_ubytovani_akce", "akce", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
