//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ebis.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbLocation : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbLocation object using the connection string found in the 'dbLocation' section of the application configuration file.
        /// </summary>
        public dbLocation() : base("name=dbLocation", "dbLocation")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbLocation object.
        /// </summary>
        public dbLocation(string connectionString) : base(connectionString, "dbLocation")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbLocation object.
        /// </summary>
        public dbLocation(EntityConnection connection) : base(connection, "dbLocation")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<lokace> lokace
        {
            get
            {
                if ((_lokace == null))
                {
                    _lokace = base.CreateObjectSet<lokace>("lokace");
                }
                return _lokace;
            }
        }
        private ObjectSet<lokace> _lokace;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the lokace EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolokace(lokace lokace)
        {
            base.AddObject("lokace", lokace);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbLocationModel", Name="lokace")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lokace : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new lokace object.
        /// </summary>
        /// <param name="pk_id">Initial value of the pk_id property.</param>
        /// <param name="jmeno">Initial value of the jmeno property.</param>
        /// <param name="adresa">Initial value of the adresa property.</param>
        /// <param name="gps">Initial value of the gps property.</param>
        /// <param name="link">Initial value of the link property.</param>
        public static lokace Createlokace(global::System.Int32 pk_id, global::System.String jmeno, global::System.String adresa, global::System.String gps, global::System.String link)
        {
            lokace lokace = new lokace();
            lokace.pk_id = pk_id;
            lokace.jmeno = jmeno;
            lokace.adresa = adresa;
            lokace.gps = gps;
            lokace.link = link;
            return lokace;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pk_id
        {
            get
            {
                return _pk_id;
            }
            set
            {
                if (_pk_id != value)
                {
                    Onpk_idChanging(value);
                    ReportPropertyChanging("pk_id");
                    _pk_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pk_id");
                    Onpk_idChanged();
                }
            }
        }
        private global::System.Int32 _pk_id;
        partial void Onpk_idChanging(global::System.Int32 value);
        partial void Onpk_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String jmeno
        {
            get
            {
                return _jmeno;
            }
            set
            {
                OnjmenoChanging(value);
                ReportPropertyChanging("jmeno");
                _jmeno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("jmeno");
                OnjmenoChanged();
            }
        }
        private global::System.String _jmeno;
        partial void OnjmenoChanging(global::System.String value);
        partial void OnjmenoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String adresa
        {
            get
            {
                return _adresa;
            }
            set
            {
                OnadresaChanging(value);
                ReportPropertyChanging("adresa");
                _adresa = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("adresa");
                OnadresaChanged();
            }
        }
        private global::System.String _adresa;
        partial void OnadresaChanging(global::System.String value);
        partial void OnadresaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gps
        {
            get
            {
                return _gps;
            }
            set
            {
                OngpsChanging(value);
                ReportPropertyChanging("gps");
                _gps = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("gps");
                OngpsChanged();
            }
        }
        private global::System.String _gps;
        partial void OngpsChanging(global::System.String value);
        partial void OngpsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String link
        {
            get
            {
                return _link;
            }
            set
            {
                OnlinkChanging(value);
                ReportPropertyChanging("link");
                _link = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("link");
                OnlinkChanged();
            }
        }
        private global::System.String _link;
        partial void OnlinkChanging(global::System.String value);
        partial void OnlinkChanged();

        #endregion

    
    }

    #endregion

    
}
